host_addr: ":8080"
start_url: "https://www.vesti.ru/"
count_workers: 50

elastic:
  addr: "http://elasticsearch:9200"
  index: "webpages"

redis:
  addr: "redis:6379"
  password: ""
  queue_key: "url_queue"
  set_key: "url_set"

postgres:
  host: "postgres"
  port: 5432
  user: "user"
  password: "password"
  dbname: "postgres"
  sslmode: "disable"