host_addr: ":8080"
start_url: "https://www.vesti.ru/"
count_workers: 50

elastic:
  addr: "http://localhost:9200"
  index: "webpages"

redis:
  addr: "localhost:6379"
  password: ""
  queue_key: "url_queue"
  set_key: "url_set"

postgres:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "qwerty"
  dbname: "postgres"
  sslmode: "disable"